### ISSUE TITLE
Problem in installig stcor 

### ISSUE THREAD

**Issue by anirba** [alstat/stcor#1]
while installing package "stcor" i have this error please help

Downloading github repo alstat/stcor@master
Installing stcor
"C:/PROGRA~1/R/R-30~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/User/AppData/Local/Temp/RtmpIVfnVs/devtoolsce02b432e27/alstat-stcor-3714ef0"  \
  --library="C:/Users/User/Documents/R/win-library/3.0" --install-tests 
- installing _source_ package 'stcor' ...
  *\* libs

**\* arch - i386
ERROR: compilation failed for package 'stcor'
- removing 'C:/Users/User/Documents/R/win-library/3.0/stcor'
  Error: Command failed (1)
  In addition: Warning message:
  Username parameter is deprecated. Please use alstat/stcor

**Comment by alstat** [comment]
Hi, try running the following:

```
install.packages("devtools")

library(devtools)
install_github("alstat/stcor")
```

**Comment by anirba** [comment]
Thanks for the reply...... but still the same error...... is it anything to do with "Rtools"??

Downloading github repo alstat/stcor@master
Installing stcor
"C:/PROGRA~1/R/R-30~1.2/bin/x64/R" --vanilla CMD INSTALL  \
  "C:/Users/User/AppData/Local/Temp/RtmpIVfnVs/devtoolsce07c5b22ba/alstat-stcor-3714ef0"  \
  --library="C:/Users/User/Documents/R/win-library/3.0" --install-tests 
- installing _source_ package 'stcor' ...
  *\* libs

**\* arch - i386
ERROR: compilation failed for package 'stcor'
- removing 'C:/Users/User/Documents/R/win-library/3.0/stcor'
  Error: Command failed (1)

**Comment by alstat** [comment]
Yes, make sure you have successfully installed Rtools. If you are using RStudio, it will automatically recommends you to install Rtools when installing devtools.

**Comment by anirba** [comment]
Thanks it worked.....i installed the wrong version of rtools.....
